// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOGTY3p5NxzfuQlQcyBPXOEiIGUrK_l7E',
    appId: '1:22179222746:web:1e81de6f3e616f6dabc1e3',
    messagingSenderId: '22179222746',
    projectId: 'brasiltoon',
    authDomain: 'brasiltoon.firebaseapp.com',
    storageBucket: 'brasiltoon.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgGt6GGKxy0DBKi_NzfoTNifDfUaRtvuQ',
    appId: '1:22179222746:android:190fbaf2e80fae75abc1e3',
    messagingSenderId: '22179222746',
    projectId: 'brasiltoon',
    storageBucket: 'brasiltoon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxrXwKE-Nhxdr9X8wrCxG38yyIYuGMxWU',
    appId: '1:22179222746:ios:df08f03c96c4a7b7abc1e3',
    messagingSenderId: '22179222746',
    projectId: 'brasiltoon',
    storageBucket: 'brasiltoon.appspot.com',
    iosBundleId: 'com.example.brasiltoon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxrXwKE-Nhxdr9X8wrCxG38yyIYuGMxWU',
    appId: '1:22179222746:ios:df08f03c96c4a7b7abc1e3',
    messagingSenderId: '22179222746',
    projectId: 'brasiltoon',
    storageBucket: 'brasiltoon.appspot.com',
    iosBundleId: 'com.example.brasiltoon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOGTY3p5NxzfuQlQcyBPXOEiIGUrK_l7E',
    appId: '1:22179222746:web:98695e0465fb6decabc1e3',
    messagingSenderId: '22179222746',
    projectId: 'brasiltoon',
    authDomain: 'brasiltoon.firebaseapp.com',
    storageBucket: 'brasiltoon.appspot.com',
  );

}